
name = "DashTvlwc"
uuid = "1b08a953-4be3-4667-9a23-2871b3b2b9b9"
authors = ["Kwan Yu, WU <wukwanyutyson@gmail.com>"]
version = "0.1.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
